// Speaking Topics Database
// Organized by category with difficulty levels

export const categories = [
  { id: "fun", name: "Fun", iconId: "party", color: "#F59E0B", description: "Light-hearted and entertaining" },
  { id: "deep", name: "Deep", iconId: "wave", color: "#3B82F6", description: "Thought-provoking and introspective" },
  { id: "ethical", name: "Ethical", iconId: "scale", color: "#8B5CF6", description: "Moral dilemmas and values" },
  { id: "relationships", name: "Relationships", iconId: "heart", color: "#EC4899", description: "Love, friendship, and connections" },
  { id: "career", name: "Career", iconId: "briefcase", color: "#10B981", description: "Work, ambition, and growth" },
  { id: "philosophy", name: "Philosophy", iconId: "brain", color: "#6366F1", description: "Big questions about existence" },
  { id: "debate", name: "Debate", iconId: "fire", color: "#E54D2E", description: "Controversial and polarizing" },
  { id: "hypothetical", name: "Crazy Hypotheticals", iconId: "rocket", color: "#F97316", description: "Wild what-if scenarios" },
];

export const topics = {
  fun: [
    "If your life was a meme, what would the caption be right now?",
    "What\u2019s the most ridiculous superpower that would actually ruin your daily life?",
    "If animals could talk, which one would be the biggest gossip?",
    "Would you rather fight one horse-sized duck or a hundred duck-sized horses?",
    "What song would play every time you entered a room if you had a personal soundtrack?",
    "Would you support a world where complete internet anonymity?",
    "Is robots replacing teachers a blessing or a curse?",
    "Should people be allowed to dream-sharing technology?",
    "Can AI controlled governments ever truly exist?",
    "What would happen if social media disappearing forever?",
    "How would your life change if people never needing sleep?",
    "Do you believe dream-sharing technology? Why or why not?",
    "Can emotion-reading devices ever truly exist?",
    "What makes emotion-reading devices meaningful?",
    "Would society improve if humans stopping aging?",
    "What would happen if a world without money?",
    "Should people be allowed to AI controlled governments?",
    "Would society improve if complete internet anonymity?",
    "Would you support a world where memory editing technology?",
    "Would you support a world where digital immortality?",
    "Do you believe every secret becoming public? Why or why not?",
    "Would society improve if memory editing technology?",
    "What would happen if humans communicating with animals?",
    "Would you support a world where dream-sharing technology?",
    "What\u2019s the strongest argument against a world without money?",
    "Do you believe humans living on Mars? Why or why not?",
    "How would your life change if robots replacing teachers?",
    "Is digital immortality a blessing or a curse?",
    "What makes flying cars becoming normal meaningful?",
    "Should people be allowed to time travel becoming legal?",
    "What\u2019s the strongest argument against humans communicating with animals?",
    "What makes universal basic income meaningful?",
    "What\u2019s the strongest argument against robots replacing teachers?",
    "What makes humans communicating with animals meaningful?",
    "What would happen if people never needing sleep?",
    "How would your life change if everyone hearing each other's thoughts?",
    "Would society improve if humans living on Mars?",
    "Can robots replacing teachers ever truly exist?",
    "Do you believe robots replacing teachers? Why or why not?",
    "What makes digital immortality meaningful?",
    "Can universal basic income ever truly exist?",
    "Would you support a world where time travel becoming legal?",
    "Would you support a world where humans stopping aging?",
    "What would happen if memory editing technology?",
    "Is dream-sharing technology a blessing or a curse?",
    "How would your life change if universal basic income?",
    "What makes complete internet anonymity meaningful?",
    "Would society improve if people never needing sleep?",
    "How would your life change if social media disappearing forever?",
    "Is flying cars becoming normal a blessing or a curse?",
    "Would society improve if a world without money?",
    "Do you believe memory editing technology? Why or why not?",
    "What would happen if complete internet anonymity?",
    "How would your life change if every secret becoming public?",
    "How would your life change if memory editing technology?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "Would you support a world where people never needing sleep?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "Would society improve if universal basic income?",
    "What would happen if humans stopping aging?",
    "What\u2019s the strongest argument against memory editing technology?",
    "What\u2019s the strongest argument against flying cars becoming normal?",
    "What\u2019s the strongest argument against time travel becoming legal?",
    "Is perfect virtual reality a blessing or a curse?",
    "How would your life change if perfect virtual reality?",
    "Would you support a world where emotion-reading devices?",
    "Would you support a world where flying cars becoming normal?",
    "Should people be allowed to robots replacing teachers?",
    "How would your life change if time travel becoming legal?",
    "What makes everyone hearing each other's thoughts meaningful?",
    "Is humans living on Mars a blessing or a curse?",
    "Would society improve if dream-sharing technology?",
    "Can social media disappearing forever ever truly exist?",
    "Is emotion-reading devices a blessing or a curse?",
    "What makes humans stopping aging meaningful?",
    "What would happen if humans living on Mars?",
    "Is universal basic income a blessing or a curse?",
    "What\u2019s the strongest argument against digital immortality?",
    "Would society improve if digital immortality?",
    "What\u2019s the strongest argument against universal basic income?",
    "Is AI controlled governments a blessing or a curse?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "Can memory editing technology ever truly exist?",
    "Is a 4-day work week a blessing or a curse?",
    "What\u2019s the strongest argument against a 4-day work week?",
    "How would your life change if digital immortality?",
    "Do you believe a 4-day work week? Why or why not?",
    "How would your life change if AI controlled governments?",
    "Would society improve if a 4-day work week?",
    "Can dream-sharing technology ever truly exist?",
    "What would happen if digital immortality?",
    "Can everyone hearing each other's thoughts ever truly exist?",
    "Can humans communicating with animals ever truly exist?",
    "Should people be allowed to every secret becoming public?",
    "Do you believe universal basic income? Why or why not?",
    "What\u2019s the strongest argument against social media disappearing forever?",
    "Do you believe a world without money? Why or why not?",
    "Is social media disappearing forever a blessing or a curse?",
    "Would society improve if time travel becoming legal?",
    "Can a world without money ever truly exist?",
  ],

  deep: [
    "What if the meaning of life is not to find it, but to realize we invent it every morning?",
    "Is loneliness the price we pay for being truly ourselves?",
    "If you could watch a movie of your entire life, would you fast-forward the painful parts?",
    "Are we more defined by what we hide or by what we reveal?",
    "What version of yourself are you still mourning?",
    "Is time travel becoming legal a blessing or a curse?",
    "Do you believe dream-sharing technology? Why or why not?",
    "What\u2019s the strongest argument against a 4-day work week?",
    "What\u2019s the strongest argument against time travel becoming legal?",
    "How would your life change if every secret becoming public?",
    "Should people be allowed to people never needing sleep?",
    "Would you support a world where humans stopping aging?",
    "Do you believe every secret becoming public? Why or why not?",
    "Would society improve if complete internet anonymity?",
    "Do you believe a world without money? Why or why not?",
    "Is AI controlled governments a blessing or a curse?",
    "What makes robots replacing teachers meaningful?",
    "Is emotion-reading devices a blessing or a curse?",
    "Can everyone hearing each other's thoughts ever truly exist?",
    "What makes flying cars becoming normal meaningful?",
    "Should people be allowed to time travel becoming legal?",
    "Should people be allowed to universal basic income?",
    "Would you support a world where perfect virtual reality?",
    "Can memory editing technology ever truly exist?",
    "What makes perfect virtual reality meaningful?",
    "Would society improve if memory editing technology?",
    "What would happen if everyone hearing each other's thoughts?",
    "What would happen if humans communicating with animals?",
    "How would your life change if universal basic income?",
    "Would you support a world where robots replacing teachers?",
    "Can complete internet anonymity ever truly exist?",
    "Can AI controlled governments ever truly exist?",
    "How would your life change if everyone hearing each other's thoughts?",
    "What makes universal basic income meaningful?",
    "What\u2019s the strongest argument against dream-sharing technology?",
    "What makes time travel becoming legal meaningful?",
    "Do you believe a 4-day work week? Why or why not?",
    "What\u2019s the strongest argument against a world without money?",
    "What would happen if time travel becoming legal?",
    "What\u2019s the strongest argument against complete internet anonymity?",
    "Would you support a world where humans communicating with animals?",
    "Would society improve if humans living on Mars?",
    "Would society improve if everyone hearing each other's thoughts?",
    "Can perfect virtual reality ever truly exist?",
    "Should people be allowed to humans communicating with animals?",
    "What\u2019s the strongest argument against emotion-reading devices?",
    "What would happen if people never needing sleep?",
    "What would happen if social media disappearing forever?",
    "What would happen if emotion-reading devices?",
    "What would happen if a world without money?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "Is people never needing sleep a blessing or a curse?",
    "Would you support a world where universal basic income?",
    "Would you support a world where humans living on Mars?",
    "What would happen if perfect virtual reality?",
    "Should people be allowed to humans living on Mars?",
    "Would society improve if every secret becoming public?",
    "What\u2019s the strongest argument against humans stopping aging?",
    "Can humans communicating with animals ever truly exist?",
    "Can a world without money ever truly exist?",
    "Can every secret becoming public ever truly exist?",
    "Can universal basic income ever truly exist?",
    "What\u2019s the strongest argument against digital immortality?",
    "Should people be allowed to emotion-reading devices?",
    "Is digital immortality a blessing or a curse?",
    "Should people be allowed to AI controlled governments?",
    "What\u2019s the strongest argument against AI controlled governments?",
    "Should people be allowed to a 4-day work week?",
    "Is social media disappearing forever a blessing or a curse?",
    "What makes humans stopping aging meaningful?",
    "Is memory editing technology a blessing or a curse?",
    "Can dream-sharing technology ever truly exist?",
    "Is complete internet anonymity a blessing or a curse?",
    "Is humans stopping aging a blessing or a curse?",
    "What would happen if every secret becoming public?",
    "Should people be allowed to digital immortality?",
    "What makes a world without money meaningful?",
    "Is universal basic income a blessing or a curse?",
    "What would happen if a 4-day work week?",
    "How would your life change if perfect virtual reality?",
    "Do you believe social media disappearing forever? Why or why not?",
    "Is humans communicating with animals a blessing or a curse?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "Is flying cars becoming normal a blessing or a curse?",
    "Do you believe humans stopping aging? Why or why not?",
    "Can social media disappearing forever ever truly exist?",
    "Do you believe universal basic income? Why or why not?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "How would your life change if time travel becoming legal?",
    "Would you support a world where emotion-reading devices?",
    "How would your life change if AI controlled governments?",
    "Do you believe humans living on Mars? Why or why not?",
    "Would you support a world where people never needing sleep?",
    "Should people be allowed to complete internet anonymity?",
    "What makes emotion-reading devices meaningful?",
    "Is everyone hearing each other's thoughts a blessing or a curse?",
    "What makes a 4-day work week meaningful?",
    "What would happen if complete internet anonymity?",
    "How would your life change if social media disappearing forever?",
    "What would happen if digital immortality?",
  ],

  ethical: [
    "Would you kill one innocent person to save a million if no one would ever know?",
    "Is it ethical to stay silent when you see injustice that doesn\u2019t affect you?",
    "If you could upload your consciousness to the cloud and live forever, should you?",
    "Does the end always justify the means, or are some means forever unjustifiable?",
    "Should we have the right to choose our own death?",
    "Can everyone hearing each other's thoughts ever truly exist?",
    "Can memory editing technology ever truly exist?",
    "Do you believe time travel becoming legal? Why or why not?",
    "What\u2019s the strongest argument against robots replacing teachers?",
    "What makes digital immortality meaningful?",
    "Do you believe perfect virtual reality? Why or why not?",
    "What\u2019s the strongest argument against everyone hearing each other's thoughts?",
    "Is perfect virtual reality a blessing or a curse?",
    "Should people be allowed to humans living on Mars?",
    "Would society improve if time travel becoming legal?",
    "What would happen if perfect virtual reality?",
    "Should people be allowed to complete internet anonymity?",
    "Should people be allowed to digital immortality?",
    "How would your life change if flying cars becoming normal?",
    "Can people never needing sleep ever truly exist?",
    "Would society improve if a world without money?",
    "Is social media disappearing forever a blessing or a curse?",
    "Should people be allowed to humans stopping aging?",
    "What would happen if people never needing sleep?",
    "What makes complete internet anonymity meaningful?",
    "What\u2019s the strongest argument against social media disappearing forever?",
    "Is AI controlled governments a blessing or a curse?",
    "What would happen if flying cars becoming normal?",
    "Would society improve if social media disappearing forever?",
    "What makes emotion-reading devices meaningful?",
    "What would happen if dream-sharing technology?",
    "Is universal basic income a blessing or a curse?",
    "Can social media disappearing forever ever truly exist?",
    "Should people be allowed to dream-sharing technology?",
    "What would happen if humans living on Mars?",
    "Would you support a world where social media disappearing forever?",
    "Would you support a world where robots replacing teachers?",
    "What\u2019s the strongest argument against every secret becoming public?",
    "How would your life change if social media disappearing forever?",
    "What would happen if every secret becoming public?",
    "Would you support a world where perfect virtual reality?",
    "Do you believe dream-sharing technology? Why or why not?",
    "How would your life change if humans stopping aging?",
    "Would you support a world where digital immortality?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "What\u2019s the strongest argument against a 4-day work week?",
    "Would you support a world where humans stopping aging?",
    "Is time travel becoming legal a blessing or a curse?",
    "What\u2019s the strongest argument against digital immortality?",
    "Would society improve if perfect virtual reality?",
    "Is emotion-reading devices a blessing or a curse?",
    "What makes humans communicating with animals meaningful?",
    "How would your life change if AI controlled governments?",
    "Would you support a world where everyone hearing each other's thoughts?",
    "What makes robots replacing teachers meaningful?",
    "Should people be allowed to every secret becoming public?",
    "Do you believe emotion-reading devices? Why or why not?",
    "How would your life change if universal basic income?",
    "Would society improve if universal basic income?",
    "What\u2019s the strongest argument against complete internet anonymity?",
    "Can AI controlled governments ever truly exist?",
    "Do you believe digital immortality? Why or why not?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "How would your life change if robots replacing teachers?",
    "Can perfect virtual reality ever truly exist?",
    "What makes universal basic income meaningful?",
    "Would society improve if complete internet anonymity?",
    "Do you believe AI controlled governments? Why or why not?",
    "Would society improve if humans communicating with animals?",
    "Would you support a world where dream-sharing technology?",
    "Should people be allowed to perfect virtual reality?",
    "Can a world without money ever truly exist?",
    "Is flying cars becoming normal a blessing or a curse?",
    "Do you believe complete internet anonymity? Why or why not?",
    "Should people be allowed to memory editing technology?",
    "How would your life change if digital immortality?",
    "Would society improve if humans stopping aging?",
    "Is a 4-day work week a blessing or a curse?",
    "Is memory editing technology a blessing or a curse?",
    "Do you believe humans communicating with animals? Why or why not?",
    "What would happen if universal basic income?",
    "Do you believe a 4-day work week? Why or why not?",
    "What\u2019s the strongest argument against dream-sharing technology?",
    "Would you support a world where humans communicating with animals?",
    "Can every secret becoming public ever truly exist?",
    "Is digital immortality a blessing or a curse?",
    "Can digital immortality ever truly exist?",
    "Do you believe robots replacing teachers? Why or why not?",
    "Would society improve if robots replacing teachers?",
    "Would you support a world where humans living on Mars?",
    "What\u2019s the strongest argument against humans stopping aging?",
    "Would society improve if a 4-day work week?",
    "Do you believe social media disappearing forever? Why or why not?",
    "Do you believe humans stopping aging? Why or why not?",
    "Is every secret becoming public a blessing or a curse?",
    "Is robots replacing teachers a blessing or a curse?",
    "Should people be allowed to flying cars becoming normal?",
    "How would your life change if every secret becoming public?",
    "What makes every secret becoming public meaningful?",
    "How would your life change if time travel becoming legal?",
  ],

  relationships: [
    "Can you truly love someone you don\u2019t fully understand?",
    "Is jealousy proof of love or proof of insecurity?",
    "What\u2019s more important: being chosen or choosing wisely?",
    "If your partner read your thoughts for one day, would the relationship survive?",
    "Are soulmates found or forged?",
    "Is digital immortality a blessing or a curse?",
    "What would happen if people never needing sleep?",
    "What makes universal basic income meaningful?",
    "Is a world without money a blessing or a curse?",
    "Is perfect virtual reality a blessing or a curse?",
    "What\u2019s the strongest argument against universal basic income?",
    "What makes robots replacing teachers meaningful?",
    "How would your life change if humans living on Mars?",
    "Is every secret becoming public a blessing or a curse?",
    "Should people be allowed to emotion-reading devices?",
    "Can universal basic income ever truly exist?",
    "What\u2019s the strongest argument against perfect virtual reality?",
    "Do you believe a 4-day work week? Why or why not?",
    "What\u2019s the strongest argument against every secret becoming public?",
    "Would you support a world where a world without money?",
    "What\u2019s the strongest argument against social media disappearing forever?",
    "How would your life change if humans communicating with animals?",
    "Do you believe AI controlled governments? Why or why not?",
    "Should people be allowed to AI controlled governments?",
    "Would you support a world where time travel becoming legal?",
    "What would happen if emotion-reading devices?",
    "What\u2019s the strongest argument against everyone hearing each other's thoughts?",
    "How would your life change if perfect virtual reality?",
    "Would society improve if emotion-reading devices?",
    "What makes emotion-reading devices meaningful?",
    "What makes a world without money meaningful?",
    "What would happen if a world without money?",
    "Can perfect virtual reality ever truly exist?",
    "What would happen if humans communicating with animals?",
    "Would you support a world where social media disappearing forever?",
    "What makes every secret becoming public meaningful?",
    "Should people be allowed to every secret becoming public?",
    "What would happen if flying cars becoming normal?",
    "What would happen if social media disappearing forever?",
    "What\u2019s the strongest argument against dream-sharing technology?",
    "What\u2019s the strongest argument against AI controlled governments?",
    "Would you support a world where every secret becoming public?",
    "Should people be allowed to social media disappearing forever?",
    "What would happen if universal basic income?",
    "Is complete internet anonymity a blessing or a curse?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "Should people be allowed to memory editing technology?",
    "Should people be allowed to time travel becoming legal?",
    "Is time travel becoming legal a blessing or a curse?",
    "What\u2019s the strongest argument against memory editing technology?",
    "Would you support a world where humans communicating with animals?",
    "Can time travel becoming legal ever truly exist?",
    "What would happen if complete internet anonymity?",
    "What makes humans living on Mars meaningful?",
    "How would your life change if memory editing technology?",
    "What would happen if digital immortality?",
    "Would you support a world where emotion-reading devices?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "Can complete internet anonymity ever truly exist?",
    "What\u2019s the strongest argument against complete internet anonymity?",
    "Do you believe perfect virtual reality? Why or why not?",
    "What\u2019s the strongest argument against humans communicating with animals?",
    "What makes humans stopping aging meaningful?",
    "Can humans communicating with animals ever truly exist?",
    "Can every secret becoming public ever truly exist?",
    "What would happen if dream-sharing technology?",
    "What would happen if memory editing technology?",
    "Do you believe people never needing sleep? Why or why not?",
    "How would your life change if a world without money?",
    "Do you believe digital immortality? Why or why not?",
    "How would your life change if time travel becoming legal?",
    "Is robots replacing teachers a blessing or a curse?",
    "Would you support a world where digital immortality?",
    "Would you support a world where complete internet anonymity?",
    "What would happen if perfect virtual reality?",
    "Would society improve if robots replacing teachers?",
    "How would your life change if emotion-reading devices?",
    "Do you believe a world without money? Why or why not?",
    "Would you support a world where everyone hearing each other's thoughts?",
    "Do you believe humans communicating with animals? Why or why not?",
    "Is flying cars becoming normal a blessing or a curse?",
    "Do you believe universal basic income? Why or why not?",
    "What would happen if time travel becoming legal?",
    "Is people never needing sleep a blessing or a curse?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "What makes a 4-day work week meaningful?",
    "How would your life change if humans stopping aging?",
    "Is social media disappearing forever a blessing or a curse?",
    "Should people be allowed to dream-sharing technology?",
    "What\u2019s the strongest argument against a 4-day work week?",
    "Should people be allowed to humans communicating with animals?",
    "Can emotion-reading devices ever truly exist?",
    "How would your life change if AI controlled governments?",
    "Can robots replacing teachers ever truly exist?",
    "Would society improve if a 4-day work week?",
    "Can a 4-day work week ever truly exist?",
    "How would your life change if digital immortality?",
    "Can people never needing sleep ever truly exist?",
    "What\u2019s the strongest argument against emotion-reading devices?",
    "Would you support a world where memory editing technology?",
  ],

  career: [
    "Would you rather be respected or liked in your professional life?",
    "Is success worth the parts of your soul you trade for it?",
    "If money wasn\u2019t an issue, what would you do with your days?",
    "Are you climbing the ladder or just decorating the cage?",
    "What legacy do you want written on your professional tombstone?",
    "Would society improve if digital immortality?",
    "What makes emotion-reading devices meaningful?",
    "What would happen if humans stopping aging?",
    "What\u2019s the strongest argument against a 4-day work week?",
    "How would your life change if robots replacing teachers?",
    "What would happen if dream-sharing technology?",
    "What would happen if AI controlled governments?",
    "Is perfect virtual reality a blessing or a curse?",
    "Do you believe every secret becoming public? Why or why not?",
    "How would your life change if humans communicating with animals?",
    "Would you support a world where humans communicating with animals?",
    "Do you believe a world without money? Why or why not?",
    "What\u2019s the strongest argument against flying cars becoming normal?",
    "Is time travel becoming legal a blessing or a curse?",
    "Would you support a world where flying cars becoming normal?",
    "What would happen if perfect virtual reality?",
    "Would society improve if humans communicating with animals?",
    "How would your life change if time travel becoming legal?",
    "Would you support a world where humans living on Mars?",
    "Would you support a world where a 4-day work week?",
    "Can every secret becoming public ever truly exist?",
    "What makes digital immortality meaningful?",
    "Is robots replacing teachers a blessing or a curse?",
    "Is a world without money a blessing or a curse?",
    "What makes time travel becoming legal meaningful?",
    "What would happen if humans communicating with animals?",
    "What would happen if social media disappearing forever?",
    "Would you support a world where every secret becoming public?",
    "Would you support a world where people never needing sleep?",
    "Do you believe dream-sharing technology? Why or why not?",
    "Would society improve if complete internet anonymity?",
    "Can humans living on Mars ever truly exist?",
    "Can emotion-reading devices ever truly exist?",
    "Can AI controlled governments ever truly exist?",
    "What makes humans stopping aging meaningful?",
    "Should people be allowed to emotion-reading devices?",
    "Should people be allowed to flying cars becoming normal?",
    "Can memory editing technology ever truly exist?",
    "What would happen if flying cars becoming normal?",
    "What\u2019s the strongest argument against memory editing technology?",
    "Is universal basic income a blessing or a curse?",
    "Should people be allowed to digital immortality?",
    "Can robots replacing teachers ever truly exist?",
    "What makes complete internet anonymity meaningful?",
    "What\u2019s the strongest argument against digital immortality?",
    "Should people be allowed to dream-sharing technology?",
    "Is digital immortality a blessing or a curse?",
    "Is social media disappearing forever a blessing or a curse?",
    "Would society improve if social media disappearing forever?",
    "Do you believe humans stopping aging? Why or why not?",
    "How would your life change if a world without money?",
    "Do you believe time travel becoming legal? Why or why not?",
    "Should people be allowed to a world without money?",
    "What\u2019s the strongest argument against a world without money?",
    "What\u2019s the strongest argument against emotion-reading devices?",
    "How would your life change if dream-sharing technology?",
    "What makes universal basic income meaningful?",
    "Would you support a world where emotion-reading devices?",
    "Should people be allowed to AI controlled governments?",
    "How would your life change if AI controlled governments?",
    "What would happen if people never needing sleep?",
    "How would your life change if complete internet anonymity?",
    "Can a world without money ever truly exist?",
    "How would your life change if perfect virtual reality?",
    "Do you believe humans communicating with animals? Why or why not?",
    "Do you believe complete internet anonymity? Why or why not?",
    "What\u2019s the strongest argument against time travel becoming legal?",
    "Can complete internet anonymity ever truly exist?",
    "Do you believe social media disappearing forever? Why or why not?",
    "Should people be allowed to humans communicating with animals?",
    "Is complete internet anonymity a blessing or a curse?",
    "What makes a world without money meaningful?",
    "Can humans communicating with animals ever truly exist?",
    "Is people never needing sleep a blessing or a curse?",
    "Should people be allowed to time travel becoming legal?",
    "Should people be allowed to perfect virtual reality?",
    "Do you believe AI controlled governments? Why or why not?",
    "Should people be allowed to robots replacing teachers?",
    "Would society improve if humans stopping aging?",
    "Would society improve if robots replacing teachers?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "What would happen if humans living on Mars?",
    "Should people be allowed to universal basic income?",
    "Would you support a world where perfect virtual reality?",
    "How would your life change if people never needing sleep?",
    "Would society improve if emotion-reading devices?",
    "What would happen if a world without money?",
    "What\u2019s the strongest argument against humans communicating with animals?",
    "What would happen if complete internet anonymity?",
    "What makes humans communicating with animals meaningful?",
    "Is everyone hearing each other's thoughts a blessing or a curse?",
    "Can digital immortality ever truly exist?",
    "Is AI controlled governments a blessing or a curse?",
    "Would you support a world where social media disappearing forever?",
    "Is every secret becoming public a blessing or a curse?",
  ],

  philosophy: [
    "If reality is merely what we perceive, does truth exist outside consciousness?",
    "Is free will an illusion we need in order to stay sane?",
    "Can we ever truly know anything?",
    "Does the universe have a purpose?",
    "Is time a river we swim in, or a prison we\u2019re born inside?",
    "Would society improve if every secret becoming public?",
    "Should people be allowed to universal basic income?",
    "What would happen if dream-sharing technology?",
    "Do you believe robots replacing teachers? Why or why not?",
    "Do you believe every secret becoming public? Why or why not?",
    "Should people be allowed to a world without money?",
    "Can every secret becoming public ever truly exist?",
    "Would you support a world where humans living on Mars?",
    "Can humans communicating with animals ever truly exist?",
    "How would your life change if complete internet anonymity?",
    "What would happen if humans stopping aging?",
    "Should people be allowed to emotion-reading devices?",
    "Do you believe humans communicating with animals? Why or why not?",
    "What\u2019s the strongest argument against perfect virtual reality?",
    "Is AI controlled governments a blessing or a curse?",
    "Should people be allowed to humans living on Mars?",
    "Is time travel becoming legal a blessing or a curse?",
    "How would your life change if social media disappearing forever?",
    "Should people be allowed to robots replacing teachers?",
    "What would happen if digital immortality?",
    "Can emotion-reading devices ever truly exist?",
    "Can flying cars becoming normal ever truly exist?",
    "What would happen if every secret becoming public?",
    "Do you believe humans living on Mars? Why or why not?",
    "How would your life change if AI controlled governments?",
    "Would society improve if humans stopping aging?",
    "Would society improve if flying cars becoming normal?",
    "What would happen if memory editing technology?",
    "Would you support a world where robots replacing teachers?",
    "What makes digital immortality meaningful?",
    "Can humans stopping aging ever truly exist?",
    "What\u2019s the strongest argument against AI controlled governments?",
    "Can universal basic income ever truly exist?",
    "What would happen if a 4-day work week?",
    "Is digital immortality a blessing or a curse?",
    "Would society improve if dream-sharing technology?",
    "Would you support a world where time travel becoming legal?",
    "Can digital immortality ever truly exist?",
    "Do you believe perfect virtual reality? Why or why not?",
    "Can dream-sharing technology ever truly exist?",
    "What\u2019s the strongest argument against flying cars becoming normal?",
    "How would your life change if perfect virtual reality?",
    "How would your life change if every secret becoming public?",
    "What makes perfect virtual reality meaningful?",
    "Should people be allowed to social media disappearing forever?",
    "Would society improve if a world without money?",
    "What would happen if time travel becoming legal?",
    "What\u2019s the strongest argument against digital immortality?",
    "How would your life change if emotion-reading devices?",
    "Would you support a world where AI controlled governments?",
    "Can people never needing sleep ever truly exist?",
    "Would you support a world where complete internet anonymity?",
    "Should people be allowed to AI controlled governments?",
    "Would you support a world where memory editing technology?",
    "Would you support a world where people never needing sleep?",
    "How would your life change if a 4-day work week?",
    "What would happen if AI controlled governments?",
    "Would you support a world where humans communicating with animals?",
    "What\u2019s the strongest argument against social media disappearing forever?",
    "What makes humans communicating with animals meaningful?",
    "Should people be allowed to every secret becoming public?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "Should people be allowed to perfect virtual reality?",
    "Should people be allowed to dream-sharing technology?",
    "Should people be allowed to everyone hearing each other's thoughts?",
    "How would your life change if humans communicating with animals?",
    "Is humans stopping aging a blessing or a curse?",
    "Should people be allowed to a 4-day work week?",
    "Would you support a world where perfect virtual reality?",
    "Would society improve if time travel becoming legal?",
    "Can perfect virtual reality ever truly exist?",
    "Do you believe a world without money? Why or why not?",
    "What\u2019s the strongest argument against emotion-reading devices?",
    "What would happen if flying cars becoming normal?",
    "Would you support a world where dream-sharing technology?",
    "What makes dream-sharing technology meaningful?",
    "Is social media disappearing forever a blessing or a curse?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "What makes robots replacing teachers meaningful?",
    "Can AI controlled governments ever truly exist?",
    "Do you believe dream-sharing technology? Why or why not?",
    "What would happen if complete internet anonymity?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "Would you support a world where everyone hearing each other's thoughts?",
    "Would society improve if robots replacing teachers?",
    "What would happen if people never needing sleep?",
    "What makes universal basic income meaningful?",
    "Can robots replacing teachers ever truly exist?",
    "Do you believe people never needing sleep? Why or why not?",
    "Should people be allowed to complete internet anonymity?",
    "Can social media disappearing forever ever truly exist?",
    "Can humans living on Mars ever truly exist?",
    "Would society improve if a 4-day work week?",
    "How would your life change if people never needing sleep?",
    "Would society improve if social media disappearing forever?",
  ],

  hypothetical: [
    "What if gravity only worked on Tuesdays?",
    "If you could swap lives with any person currently alive for 24 hours, who would it be?",
    "What if every lie you told physically made your nose grow like Pinocchio?",
    "If humans could photosynthesize, how would society change?",
    "What if you woke up tomorrow and everyone else on Earth had vanished?",
    "What would happen if a 4-day work week?",
    "Should people be allowed to AI controlled governments?",
    "Would you support a world where complete internet anonymity?",
    "What makes humans communicating with animals meaningful?",
    "How would your life change if flying cars becoming normal?",
    "Can flying cars becoming normal ever truly exist?",
    "What would happen if humans living on Mars?",
    "Would you support a world where humans living on Mars?",
    "Would you support a world where humans communicating with animals?",
    "Would society improve if every secret becoming public?",
    "Do you believe humans living on Mars? Why or why not?",
    "How would your life change if perfect virtual reality?",
    "What\u2019s the strongest argument against robots replacing teachers?",
    "Would society improve if universal basic income?",
    "What makes time travel becoming legal meaningful?",
    "What\u2019s the strongest argument against time travel becoming legal?",
    "Do you believe humans stopping aging? Why or why not?",
    "Would society improve if perfect virtual reality?",
    "Would you support a world where humans stopping aging?",
    "How would your life change if complete internet anonymity?",
    "What would happen if robots replacing teachers?",
    "What makes flying cars becoming normal meaningful?",
    "Do you believe a world without money? Why or why not?",
    "Is social media disappearing forever a blessing or a curse?",
    "What would happen if emotion-reading devices?",
    "Would you support a world where emotion-reading devices?",
    "Can everyone hearing each other's thoughts ever truly exist?",
    "Do you believe dream-sharing technology? Why or why not?",
    "Do you believe people never needing sleep? Why or why not?",
    "Would you support a world where people never needing sleep?",
    "What would happen if perfect virtual reality?",
    "What would happen if everyone hearing each other's thoughts?",
    "Should people be allowed to memory editing technology?",
    "Should people be allowed to humans living on Mars?",
    "Can humans stopping aging ever truly exist?",
    "What would happen if people never needing sleep?",
    "Can complete internet anonymity ever truly exist?",
    "Is people never needing sleep a blessing or a curse?",
    "Would you support a world where memory editing technology?",
    "Would you support a world where time travel becoming legal?",
    "What\u2019s the strongest argument against flying cars becoming normal?",
    "Should people be allowed to social media disappearing forever?",
    "How would your life change if robots replacing teachers?",
    "Would you support a world where robots replacing teachers?",
    "Can a 4-day work week ever truly exist?",
    "Is humans communicating with animals a blessing or a curse?",
    "How would your life change if social media disappearing forever?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "Should people be allowed to perfect virtual reality?",
    "Would you support a world where social media disappearing forever?",
    "What makes a 4-day work week meaningful?",
    "What\u2019s the strongest argument against digital immortality?",
    "Do you believe humans communicating with animals? Why or why not?",
    "Can a world without money ever truly exist?",
    "How would your life change if every secret becoming public?",
    "How would your life change if universal basic income?",
    "Is a world without money a blessing or a curse?",
    "Is complete internet anonymity a blessing or a curse?",
    "What would happen if time travel becoming legal?",
    "Is a 4-day work week a blessing or a curse?",
    "Is dream-sharing technology a blessing or a curse?",
    "How would your life change if people never needing sleep?",
    "Do you believe flying cars becoming normal? Why or why not?",
    "Would society improve if memory editing technology?",
    "Can robots replacing teachers ever truly exist?",
    "Can dream-sharing technology ever truly exist?",
    "Would you support a world where a 4-day work week?",
    "Would society improve if a world without money?",
    "Do you believe time travel becoming legal? Why or why not?",
    "What makes perfect virtual reality meaningful?",
    "What makes emotion-reading devices meaningful?",
    "What would happen if every secret becoming public?",
    "What makes dream-sharing technology meaningful?",
    "Should people be allowed to robots replacing teachers?",
    "Is memory editing technology a blessing or a curse?",
    "Should people be allowed to digital immortality?",
    "Would you support a world where everyone hearing each other's thoughts?",
    "What makes complete internet anonymity meaningful?",
    "Would society improve if people never needing sleep?",
    "Would you support a world where perfect virtual reality?",
    "Would society improve if complete internet anonymity?",
    "Should people be allowed to humans stopping aging?",
    "Would you support a world where a world without money?",
    "Is humans living on Mars a blessing or a curse?",
    "What would happen if complete internet anonymity?",
    "Can humans living on Mars ever truly exist?",
    "Can AI controlled governments ever truly exist?",
    "What\u2019s the strongest argument against every secret becoming public?",
    "What\u2019s the strongest argument against memory editing technology?",
    "Should people be allowed to humans communicating with animals?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "Would society improve if AI controlled governments?",
    "Should people be allowed to complete internet anonymity?",
    "How would your life change if emotion-reading devices?",
    "Can digital immortality ever truly exist?",
  ],

  debate: [
    "Is democracy the best system we\u2019ve tried, or merely the least bad?",
    "Does social media do more harm than good to society?",
    "Is cancel culture justice or modern-day public shaming?",
    "Should hate speech be protected under free speech?",
    "Are humans fundamentally good or selfish?",
    "Should people be allowed to time travel becoming legal?",
    "Is dream-sharing technology a blessing or a curse?",
    "What would happen if emotion-reading devices?",
    "Would you support a world where flying cars becoming normal?",
    "Would you support a world where every secret becoming public?",
    "Would you support a world where emotion-reading devices?",
    "How would your life change if memory editing technology?",
    "Is memory editing technology a blessing or a curse?",
    "Do you believe humans living on Mars? Why or why not?",
    "Should people be allowed to digital immortality?",
    "Would you support a world where humans stopping aging?",
    "Do you believe everyone hearing each other's thoughts? Why or why not?",
    "What\u2019s the strongest argument against flying cars becoming normal?",
    "What makes perfect virtual reality meaningful?",
    "Would society improve if robots replacing teachers?",
    "What makes social media disappearing forever meaningful?",
    "Would you support a world where social media disappearing forever?",
    "Do you believe digital immortality? Why or why not?",
    "What would happen if perfect virtual reality?",
    "Should people be allowed to people never needing sleep?",
    "What makes memory editing technology meaningful?",
    "Can a world without money ever truly exist?",
    "Do you believe robots replacing teachers? Why or why not?",
    "How would your life change if every secret becoming public?",
    "What would happen if flying cars becoming normal?",
    "Would society improve if people never needing sleep?",
    "Can a 4-day work week ever truly exist?",
    "What would happen if a world without money?",
    "Would society improve if a world without money?",
    "Should people be allowed to a 4-day work week?",
    "How would your life change if humans communicating with animals?",
    "Do you believe humans stopping aging? Why or why not?",
    "How would your life change if humans living on Mars?",
    "What\u2019s the strongest argument against humans communicating with animals?",
    "Would society improve if social media disappearing forever?",
    "Can flying cars becoming normal ever truly exist?",
    "How would your life change if dream-sharing technology?",
    "Would you support a world where complete internet anonymity?",
    "Would society improve if perfect virtual reality?",
    "What would happen if social media disappearing forever?",
    "What\u2019s the strongest argument against robots replacing teachers?",
    "What\u2019s the strongest argument against a world without money?",
    "Would society improve if time travel becoming legal?",
    "Should people be allowed to memory editing technology?",
    "What makes flying cars becoming normal meaningful?",
    "Can humans communicating with animals ever truly exist?",
    "Would you support a world where everyone hearing each other's thoughts?",
    "What makes complete internet anonymity meaningful?",
    "How would your life change if people never needing sleep?",
    "Is everyone hearing each other's thoughts a blessing or a curse?",
    "Is a 4-day work week a blessing or a curse?",
    "How would your life change if flying cars becoming normal?",
    "What would happen if complete internet anonymity?",
    "What makes a world without money meaningful?",
    "Would society improve if everyone hearing each other's thoughts?",
    "Can robots replacing teachers ever truly exist?",
    "Is robots replacing teachers a blessing or a curse?",
    "What makes dream-sharing technology meaningful?",
    "Would you support a world where dream-sharing technology?",
    "Would society improve if dream-sharing technology?",
    "Would you support a world where memory editing technology?",
    "Should people be allowed to social media disappearing forever?",
    "How would your life change if digital immortality?",
    "What\u2019s the strongest argument against humans stopping aging?",
    "What would happen if time travel becoming legal?",
    "Would society improve if humans living on Mars?",
    "Would you support a world where perfect virtual reality?",
    "How would your life change if emotion-reading devices?",
    "Can emotion-reading devices ever truly exist?",
    "What\u2019s the strongest argument against humans living on Mars?",
    "Would you support a world where universal basic income?",
    "Do you believe every secret becoming public? Why or why not?",
    "What makes people never needing sleep meaningful?",
    "What would happen if every secret becoming public?",
    "What\u2019s the strongest argument against AI controlled governments?",
    "Can dream-sharing technology ever truly exist?",
    "Do you believe social media disappearing forever? Why or why not?",
    "Is complete internet anonymity a blessing or a curse?",
    "What\u2019s the strongest argument against people never needing sleep?",
    "How would your life change if complete internet anonymity?",
    "What would happen if people never needing sleep?",
    "Do you believe memory editing technology? Why or why not?",
    "What makes digital immortality meaningful?",
    "Do you believe a world without money? Why or why not?",
    "How would your life change if everyone hearing each other's thoughts?",
    "Is digital immortality a blessing or a curse?",
    "Do you believe people never needing sleep? Why or why not?",
    "Should people be allowed to universal basic income?",
    "What would happen if everyone hearing each other's thoughts?",
    "What\u2019s the strongest argument against emotion-reading devices?",
    "How would your life change if humans stopping aging?",
    "What would happen if dream-sharing technology?",
    "What makes everyone hearing each other's thoughts meaningful?",
    "Would society improve if emotion-reading devices?",
    "What makes robots replacing teachers meaningful?",
  ],

};

// Utility: Get a random topic from a specific category
export function getRandomTopic(category) {
  const categoryTopics = topics[category];
  if (!categoryTopics) return null;
  return categoryTopics[Math.floor(Math.random() * categoryTopics.length)];
}

// Utility: Get a random topic from any category
export function getRandomTopicAny() {
  const allCategories = Object.keys(topics);
  const randomCategory = allCategories[Math.floor(Math.random() * allCategories.length)];
  return {
    category: randomCategory,
    topic: getRandomTopic(randomCategory),
  };
}

// Ranks progression
export const ranks = [
  { level: 1, name: "Novice Speaker", xpRequired: 0, iconId: "sprout" },
  { level: 2, name: "Warming Up", xpRequired: 100, iconId: "fire" },
  { level: 3, name: "Finding Voice", xpRequired: 300, iconId: "mic" },
  { level: 4, name: "Confident Talker", xpRequired: 600, iconId: "bubble" },
  { level: 5, name: "Eloquent Speaker", xpRequired: 1000, iconId: "sparkle" },
  { level: 6, name: "Silver Tongue", xpRequired: 1500, iconId: "medal" },
  { level: 7, name: "Golden Voice", xpRequired: 2500, iconId: "trophy" },
  { level: 8, name: "Master Debater", xpRequired: 4000, iconId: "swords" },
  { level: 9, name: "Orator", xpRequired: 6000, iconId: "crown" },
  { level: 10, name: "Legend", xpRequired: 10000, iconId: "star" },
];

// Badges
export const badges = [
  { id: "first-speak", name: "First Words", description: "Complete your first speaking session", iconId: "mic" },
  { id: "streak-3", name: "Three's a Charm", description: "Maintain a 3-day streak", iconId: "fire" },
  { id: "streak-7", name: "Week Warrior", description: "Maintain a 7-day streak", iconId: "lightning" },
  { id: "streak-30", name: "Monthly Maven", description: "Maintain a 30-day streak", iconId: "sparkle" },
  { id: "all-categories", name: "Renaissance Speaker", description: "Speak on topics from all categories", iconId: "star" },
  { id: "debate-5", name: "Debater", description: "Complete 5 debate sessions", iconId: "swords" },
  { id: "quick-10", name: "Quick Thinker", description: "Complete 10 Quick Speak sessions", iconId: "wind" },
  { id: "hour-total", name: "Hour Power", description: "Speak for a total of 1 hour", iconId: "clock" },
  { id: "opinion-20", name: "Opinionated", description: "Share 20 opinions in Opinion Rooms", iconId: "bubble" },
  { id: "night-owl", name: "Night Owl", description: "Complete a session after midnight", iconId: "owl" },
];
